[package]
name = "mimicry-emulator-linux"
version = "0.1.0"
authors = ["ve5li <ve5li@tuta.io>"]

[dependencies]
#common = { git = "https://github.com/ve5li/mimicry/emulator/common" }
common = { path = "../common" }
sfml = { git = "https://github.com/JeremyLetang/rust-sfml" }
